# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: My Own Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
    - name: My first step
      run: echo "Hello World!"
    - name: My second step
      run: echo "Foo Bar!"
      
  Second_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wahoo!" >> output.txt
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-file
          path: output.txt

  Third_Job:
    runs-on: ubuntu-latest
    needs: Second_Job
    steps:
      - run: echo "We Waited"
        name: A waiting job
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-file
      - run: cat output.txt
